#version: "3"
services:
  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    extra_hosts: ['host.docker.internal:host-gateway']
    restart: always
    ports:
      - "9411:9411"
# Zipkin: http://localhost:9411/zipkin/

  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"
  # Jaeger: http://localhost:16686/